name: CI

on: [push]

defaults:
  run:
    working-directory: "my-app 2"

jobs:
  run-tests:
    name: Lint, Unit and E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install
        # cannot use npm ci because your repo has NO package-lock.json

      # Comment if eslint fails
      # - name: Run ESLint
      #   run: npm run lint

      - name: Run Jest Tests
        run: npm run ci:test

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        env:
          SECRET_COOKIE_PASSWORD: "2gyZ3GDw3LHZQKDhPmPDL3sjREVRXPr8"
        with:
          working-directory: "my-app 2"
          build: npm run build
          start: npm start
